### ISSUE TITLE
Ornery Dice should only reroll if an attack was made. 

### ISSUE THREAD

**Issue by danlangford** [hamstercrack/bmai#14]
> **Ornery (o)** Ornery dice reroll every time the player makes any attack - whether the Ornery dice participated in it or not. The only time they don't reroll is if the player passes, making no attack whatsoever.

_Originally posted by @danlangford in https://github.com/hamstercrack/bmai/discussions/11#discussioncomment-406074_

in `bmai.cpp` in method `void BMC_Game::ApplyAttackPlayer(BMC_Move &_move)` after an action is taken it spins through all the dice looking for all the ornery dice and it rerolls them. however if the action is PASS then the ornery should not reroll.

**Comment by hamstercrack** [comment]
Oh yeah, that definitely looks wrong in the code. 

In fact, the change I made to the BME_PROPERTY_MORPHING rule is unnecessary/misleading. Arguably, OnApplyAttackPlayer() could assert the following (which would be true per your fix).
````
BM_ASSERT(g_attack_type[_move.m_attack]!=BME_ATTACK_TYPE_0_0)
````

**Comment by danlangford** [comment]
im going to commit a fix and you can leave your feedback on it
